#!/bin/bash

#
# Alarma
#
# Ej de uso:
#
# nohup alarm 16:05 Dragon Ball &  
#
#

version=0.1


options () 
{
	help=$(cat <<-TEXT

	Usage:
	 $(basename $0) <time> <options> [-t] <text> 
	 $(basename $0) <time> <options> -c <command> 
	 $(basename $0) <time> <options> -f <script file> 

	Schedule a task or create an alarm

	Options:
	 -v, --verbose                  show detailed information
	 -m, --mute                     no sound (not implemented)
	 
	 -t, --text                     text for alarm
	 -c, --command                  command to be executed
	 -f, --file                     script file
	 -s, --script                   same as -f
	 
	 -h, --help                     display this help
	 -V, --version                  display version

TEXT
)

	verbose=

	case "$1" in
	-v|--verbose)
	    verbose=1
	    shift 1
	    ;;
	esac

	case "$1" in
	-V|--version)
	  	echo "$(basename $0) version $version"
	  	return
		;;
	-h|--help)
		echo -e "$help"
		return
		;;
	[0-9][0-9]:[0-9][0-9]|[0-9]:[0-9][0-9])
		case "$2" in
			-c|--command|--cmd)
			nohup ./resident "command" "$@" >/dev/null 2>&1 &
			shift
			;;
			-f|--file|-s|--script)
			nohup ./resident "script" "$@" >/dev/null 2>&1 &
			shift
			;;
			-t|--text)
			nohup ./resident "$@" >/dev/null 2>&1 &
			;;
			*)
			nohup ./resident "$@" >/dev/null 2>&1 &
		esac
		;;		
	*)		
		if [[ $# -eq 0 ]]; then
			echo -e "$help"
		else
			echo -e "$(basename $0): Unrecognized option '$1'\nTry '$(basename $0) --help' for more information";
		fi 
		return
		;;
	esac
}

options "$@"



