#!/bin/bash

LANG=en_us_88591

declare -a msg

loadconf () {
	local real=$(realpath $0)
	local base=$(dirname $real)
	source $base/cronos.conf
}

remove_task () {
	pid=$$
	echo "removing with PID=$pid"
	sed -i "/^$pid\t/d" /tmp/cronosq
}

push () {
	msg=("${msg[@]}" "$1")
}

sendmsg () {
	(dd if=/tmp/cronosp iflag=nonblock of=/dev/null) >/dev/null 2>&1

	for m in "${msg[@]}"; do
		echo -e "$m " > /tmp/cronosp
	done

	[[ ${#msg[@]} -eq 0 ]] && echo " " > /tmp/cronosp
}

dialogo () {
	zenity --question \
			    --title="Alarm" \
			    --text "<span foreground=\"#ccc\" font=\"32\">$text</span>" \
			    --timeout="$(($tm_dismiss * 60))" \
			    --ok-label="Finish" \
			    --cancel-label="Snooze" \
			    --icon-name="clock" \
			  	--window-icon="clock.png" \
			    2>/dev/null

	if [[ $? -eq 1 ]]; then
		date_jst=$(date +"%Y%m%d%H%M" -d "+$tm_rep min") 
	else 
		push "Cronos has finish"
		sendmsg
		remove_task
		exit 0
	fi	
}

function time_diff() {
	d1=$(date -u -d "$1" +"%s")
	d2=$(date -u -d "$2" +"%s")

	date -u -d "0 $d2 sec - $d1 sec" +"%H:%M:%S"
}

_alarm () {
	local cuando
	local comando
	local text
	local type

	case $1 in
		__COMMAND__)
			type="$1"; shift
			[[ ${#1} -eq 5 ]] && cuando="$1" || cuando="0$1"
			shift 2
			comando="$@"
			load="$@"
			#push "When: $cuando"
			push "Command: $comando"	
		;;
		__SCRIPT__)
			type="$1"; shift
			[[ ${#1} -eq 5 ]] && cuando="$1" || cuando="0$1"
			shift 2
			file="$@"
			load="$@"
			#push "When: $cuando"
			push "Script: script $file"
		;;
		*)	
			type="__ALARM__"
			[[ ${#1} -eq 5 ]] && cuando="$1" || cuando="0$1"
			shift
			[[ "$1" == '-t' ]] || [[ "$1" == '--text' ]] && shift
			text="$@"
			load="$@"
			#push "When: $cuando"
			push "Alarm text: $text"
		;;
	esac

	cuando=${cuando/24:/00:}
	_ahora=$(date | cut -d' ' -f2-)
	

	# Hoy o mañana 
	now=$(date +%H:%M)

	if [[ "$cuando" > "$now" ]]; then
		day="today"
		fecha=$(date --date="$cuando" | cut -f 2- -d ' ')
		
		date_ant=$(date +"%Y%m%d%H%M" -d "$fecha -$tm_ant min")
		date_dsp=$(date +"%Y%m%d%H%M" -d "$fecha +$tm_dsp min") 
		_hasta=$(date -d "$fecha -$tm_ant min" | cut -f 2- -d ' ') 	
	else
		# necesito sumar 1 día
		day="tomorrow"
		fecha=$(date --date="$cuando" | cut -f 2- -d ' ')

		date_ant=$(date +"%Y%m%d%H%M" -d "$fecha +1 day -$tm_ant min")
		date_dsp=$(date +"%Y%m%d%H%M" -d "$fecha +1 day +$tm_dsp min")
		_hasta=$(date -d "$fecha +1 day -$tm_ant min" | cut -d' ' -f2-)
	fi


	# Posibilito que la alarma se dispare antes
	date_jst=$date_ant

	ahora=$(date +"%Y%m%d%H%M"); 


	if [[ ! "$ahora" < "$date_jst" ]]; then
		zenity --question \
			    --title="Alarm" \
			    --text "<span foreground=\"#ccc\" font=\"30\">Tomorrow?</span>" \
			    --timeout="$(($tm_dismiss * 60))" \
			    --ok-label="Yes" \
			    --cancel-label="No" \
			    --icon-name="clock" \
			  	--window-icon="clock.png" \
			  	--height=150 --width=200 \
			    2>/dev/null

		if [[ $? -eq 0 ]]; then
			date_jst=$(date -d  "+1 day -5 min")
			#echo Programada para $date_jst
		else 
			    push "Aborted ***"
			    sendmsg	
			    remove_task
			    exit 1
		fi	
	fi	


	#####################################
	diff=$(time_diff "$_ahora" "$_hasta")

	#push "$_ahora ][ $_hasta"
	push "Time to accomplish: $day in $diff"
	sendmsg

	pid=$$
	echo -e "$pid\t$_hasta\t$type\t$load" >> /tmp/cronosq
	#####################################


	while [[ "$ahora" < "$date_jst" ]]; do
		ahora=$(date +"%Y%m%d%H%M")

		if [[ ! "$ahora" < "$date_jst" ]] && [[ "$ahora" < "$date_dsp" ]]; then  

			case $type in
				__COMMAND__)
					bash -c "$comando"
					remove_task
					exit 0
				;;
				__SCRIPT__)
					source "$file"
					remove_task
					exit 0
				;;
				*)
					dialogo
					remove_task
				;; 
			esac
		fi

		sleep $ts_update
	done  
}


#
# Load default values
#
loadconf


_alarm "$@"
