#!/bin/bash

LANG=en_us_88591

declare -a msg

# time interval in seconds used in completion verification
ts_update=60

invoker=$(cat /proc/$PPID/comm)

loadconf () {
	local real=$(realpath $0)
	base=$(dirname $real)
	source $base/cronos.conf
}

push () {
	if [[ ! $invoker == 'cronos' ]]; then
		echo "$1"
	else
		msg=("${msg[@]}" "$1")
	fi
}

sendmsg () {
	[[ ! $invoker == 'cronos' ]] && return 0

	dd if=/tmp/cronosp iflag=nonblock of=/dev/null >/dev/null 2>&1

	for m in "${msg[@]}"; do
		echo -e "$m " > /tmp/cronosp
	done

	[[ ${#msg[@]} -eq 0 ]] && echo " " > /tmp/cronosp
}

quit () {
	[[ ! $invoker == 'cronos' ]] && echo "quiting ..."
	exit $1
}

dialogo () {
	zenity --question \
			    --title="Alarm" \
			    --text "<span foreground=\"#ccc\" font=\"32\">$payload</span>" \
			    --timeout="$(($tm_dismiss * 60))" \
			    --ok-label="Finish" \
			    --cancel-label="Snooze" \
			    --icon-name="clock" \
			  	--window-icon="clock.png" \
			    2>/dev/null

	if [[ $? -eq 0 ]]; then
		[[ ! -z $background_process ]] && kill $background_process
		quit 0	 
	else 
		date_jst=$(date +"%Y%m%d%H%M" -d "+$tm_rep min")
	fi	
}

function time_diff() {
	d1=$(date -u -d "$1" +"%s")
	d2=$(date -u -d "$2" +"%s")

	date -u -d "0 $d2 sec - $d1 sec" +"%H:%M:%S"
}

abs_path () {
	path="$1"

	local real=$(realpath $0)
	base=$(dirname $real)

	if [[ "${path:0:1}" == "/" ]]; then
		echo "$path"
		return
	else
		realpath "$base/$path"
		return
	fi
}

playsound () {
	args=$@
	file=${args[@]}

	format=`file "$file" | cut -d: -f2`

	# mp4 / wav
	if [[ ! -z `which cvlc` ]]; then
		cvlc "$file" >/dev/null 2>&1 &
		return
	fi	

	# mp3 / wav / oog
	if [[ ! -z `which ffplay` ]]; then
		ffplay -nodisp -autoexit "$file" >/dev/null 2>&1 &
		return
	fi	

	case "$format" in
		*RIFF*) # wav
		[[ ! -z `which aplay` ]] && aplay "$file" >/dev/null 2>&1 &
		;;

		*MPEG*) # mp3
		[[ ! -z `which mpeg123` ]] && mpeg123 "$file" >/dev/null 2>&1 &
		;;
	esac
}

parse_time () {

	echo "$when" | egrep '^NOW\b' >/dev/null 2>&1
	if [[ $? -eq 0 ]]; then
		when="${when/NOW /}"
	fi

	echo "$when" | egrep '+?[0-9]+ (minutes\b|minutes\b|mins\b|min\b|hours\b|hour\b|day\b|days\b)' >/dev/null 2>&1

	if [[ $? -eq 0 ]]; then
		when=$(date +'%H:%M' -d "$when" 2>&1) 

		[[ $? -ne 0 ]] && { push "Error in time format !!!"; exit 1; } 
	fi
}

_alarm () {
	local cuando

	#push "1 - $1"
	#push "2 - $2"
	#push "3 - $3"
	#push "4 - $4"
	#push "5 - $5"

	case "$1" in
		__COMMAND__)
			type="$1"; shift
			when="$1"; parse_time
			[[ ${#when} -eq 5 ]] && cuando="$when" || cuando="0$when"
			shift 2
			payload="$@"
			#push "When: $cuando"
			push "Command: $payload"	
		;;
		__SCRIPT__)
			type="$1"; shift
			when="$1"; parse_time
			[[ ${#when} -eq 5 ]] && cuando="$when" || cuando="0$when"
			shift 
			payload="$@"
			#push "When: $cuando"
			push "Script: script $payload"
		;;
		*)	
			type="__ALARM__"
			when="$1"; parse_time
			[[ ${#when} -eq 5 ]] && cuando="$when" || cuando="0$when"
			shift
			
			mute=off
			case "$1" in
				-m|--mute)
					mute=on
					shift 
				;;
			esac

			[[ "$1" == '-t' ]] || [[ "$1" == '--text' ]] && shift
			payload="$@"
			
			#push "When: $cuando"
			push "Alarm text: $payload"
		;;
	esac

	cuando=${cuando/24:/00:}
	_ahora=$(date | cut -d' ' -f2-)
	
	#push "Type: $type"
	#push "Cuando: $cuando"
	#push "payload: $payload"
	#exit #############################

	# Hoy o mañana
	day= 
	now=$(date +%H:%M)

	if [[ "$cuando" > "$now" ]]; then
		#day="today in "
		fecha=$(date --date="$cuando" | cut -f 2- -d ' ')
		
		date_prv=$(date +"%Y%m%d%H%M" -d "$fecha -$tm_prv min")
		date_aft=$(date +"%Y%m%d%H%M" -d "$fecha +$tm_aft min") 
		_hasta=$(date -d "$fecha -$tm_prv min" | cut -f 2- -d ' ') 	
	else
		# necesito sumar 1 día
		#day="tomorrow in "
		fecha=$(date --date="$cuando" | cut -f 2- -d ' ')

		date_prv=$(date +"%Y%m%d%H%M" -d "$fecha +1 day -$tm_prv min")
		date_aft=$(date +"%Y%m%d%H%M" -d "$fecha +1 day +$tm_aft min")
		_hasta=$(date -d "$fecha +1 day -$tm_prv min" | cut -d' ' -f2-)
	fi


	# Posibilito que la alarma se dispare antes
	date_jst=$date_prv

	ahora=$(date +"%Y%m%d%H%M");
	if [[ ! "$ahora" < "$date_jst" ]]; then
		zenity --question \
			    --title="Alarm" \
			    --text "<span foreground=\"#ccc\" font=\"30\">Tomorrow?</span>" \
			    --timeout="$(($tm_dismiss * 60))" \
			    --ok-label="Yes" \
			    --cancel-label="No" \
			    --icon-name="clock" \
			  	--window-icon="clock.png" \
			  	--height=150 --width=200 \
			    2>/dev/null

		if [[ $? -eq 0 ]]; then
			date_jst=$(date -d  "+1 day -5 min")
		else 
		    push "Aborted ***"
		    sendmsg
		    quit 1
		fi	
	fi	

	#####################################
	diff=$(time_diff "$_ahora" "$_hasta")

	#push "$_ahora ][ $_hasta"
	push "Time to accomplish: ${day}$diff"

	pid=$$
	echo -e "$pid\t$_hasta\t${type//__/}\t$payload" >> /tmp/cronosq
	#####################################

	daemon
}

daemon () {
	sendmsg

	sleep $(echo 60 - $(date +%S) | bc)

	while [[ "$ahora" < "$date_jst" ]]; do
		ahora=$(date +"%Y%m%d%H%M")

		if [[ ! "$ahora" < "$date_jst" ]] && [[ "$ahora" < "$date_aft" ]]; then  

			case $type in
				__COMMAND__)
					bash -c "$payload"
					quit 0
				;;
				__SCRIPT__)
					source "$payload"
					quit 0
				;;
				*)
					[[ $mute != 'on' ]] && playsound $(abs_path "$sound")
					background_process=$!
					dialogo
				;; 
			esac
		fi

		sleep $ts_update
	done  
}

#
# Load default values
#
loadconf

_alarm "$@"
quit
